updating workflows according to checklist
zowe/zowe-cli-ims-plugin pull request #56
Opened 2023-05-05 19:38 UTC by ATorrise

Action | Description
-- | --
#1 | add [stale bot](https://github.com/zowe/zowe-cli/blob/master/.github/workflows/stale.yml)	
#2 | add [auto-comment](https://github.com/zowe/zowe-cli/blob/master/.github/workflows/auto-comment.yml) bot [on labels](https://github.com/zowe/zowe-cli/blob/master/.github/label-actions.yml)										
#3 | add issue template ([Bug](https://github.com/zowe/zowe-cli/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), [Feature](https://github.com/zowe/zowe-cli/blob/master/.github/ISSUE_TEMPLATE/feature_request.md))										
#4 | add [PR Template ](https://docs.google.com/document/u/0/d/1BvA8zNQs6QP1_gHJw7XsbEGNTTCH-v0SjM4kwMym3Cw/edit)   										
#5 | add [question redirect](https://github.com/zowe/zowe-cli/blob/master/.github/ISSUE_TEMPLATE/config.yml)										
#6 | [update all workflows to remove deprecation warnings](https://github.com/zowe/zowe-cli-web-help-generator/pull/35/files), [octorelease updates](https://github.com/zowe/zowe-cli/pull/1712)										
#7 | remove Node 14 from workflow matrix

2023-05-08 17:52 UTC, zFernand0 requested changes

2023-05-08 17:52 UTC, zFernand0 commented on .github/workflows/changelog.yml
Can we also update `awharn/check_changelog_action@v0.0.2` to `v1`?

2023-05-08 17:52 UTC, zFernand0 commented on .github/workflows/codeql.yml
> -      uses: github/codeql-action/init@v1
I believe this is missing the version number

Also, can we update the `analyze` step to v2 as well?

2023-05-08 17:52 UTC, zFernand0 commented on .github/workflows/zowe-cli-plugin.yml
> -        node-version: [14.x, 16.x, 18.x]
since node14 is gone, we can remove the "update-npm" step

2023-05-08 17:52 UTC, zFernand0 commented on .github/workflows/zowe-cli-plugin.yml
>      - name: Build Source
please update octorelease-script in the step above 😋

2023-05-10 14:56 UTC, zFernand0 requested changes

2023-05-10 14:56 UTC, zFernand0 commented on .github/workflows/zowe-cli-plugin.yml
> -        node-version: [14.x, 16.x, 18.x]
was this removed?
maybe it's my browser caching stuff
```yaml
    - name: Use NPM v8
      run: npm install -g npm@^8
```

2023-05-10 14:56 UTC, zFernand0 commented on .github/workflows/zowe-cli-plugin.yml
>        uses: zowe-actions/octorelease-script@master
this should be `zowe-actions/octorelease/script@v1`

2023-05-10 14:56 UTC, zFernand0 commented on .github/workflows/zowe-cli-plugin.yml
> -      uses: zowe-actions/octorelease-script@master
this should be `zowe-actions/octorelease/script@v1`

2023-05-11 16:09 UTC, t1m0thyj approved these changes

2023-05-11 16:26 UTC, zFernand0 approved these changes
LGTM! 
left a small comment, but not a big deal if we merge it now

2023-05-11 16:26 UTC, zFernand0 commented on .github/workflows/zowe-cli-plugin.yml
we could remove the following
```yaml
    - name: Use NPM v8
      run: npm install -g npm@^8
```

2023-05-11 16:26 UTC, merged