updating lts workflows
zowe/zowe-cli-ims-plugin pull request #57
Opened 2023-05-05 19:43 UTC by ATorrise

Action | Description
-- | --									
#6 | [update all workflows to remove deprecation warnings](https://github.com/zowe/zowe-cli-web-help-generator/pull/35/files), [octorelease updates](https://github.com/zowe/zowe-cli/pull/1712)										
#7 | remove Node 14 from workflow matrix

2023-05-08 17:54 UTC, zFernand0 requested changes

2023-05-08 17:54 UTC, zFernand0 commented on .github/workflows/changelog.yml
Can we update the `awharn/check_changelog_action@v0.0.2` to `v1`?

2023-05-08 17:54 UTC, zFernand0 commented on .github/workflows/codeql.yml
> -      uses: github/codeql-action/init@v1
please, don't forget to update the `analyze` step too 😋

2023-05-08 17:54 UTC, zFernand0 commented on .github/workflows/zowe-cli-plugin.yml
> -        node-version: [14.x, 16.x, 18.x]
we can probably remove the `update-npm` step now that node14 is gone 😋

2023-05-08 17:54 UTC, zFernand0 commented on .github/workflows/zowe-cli-plugin.yml
> -    - uses: zowe-actions/octorelease@master
I believe the version is just `v1` not `v1s` 😋

2023-05-10 15:09 UTC, zFernand0 reviewed
Should we update the version of the CLI in this branch (to remove the Audit failures)?
@t1m0thyj, thoughts?

2023-05-10 15:09 UTC, zFernand0 commented on .github/workflows/changelog.yml
> -      - zowe-v1-lts
some workflows may be missing the `zowe-v?-lts`.
but it's probably fine 😋

2023-05-11 16:12 UTC, t1m0thyj commented
> Should we update the version of the CLI in this branch (to remove the Audit failures)? @t1m0thyj, thoughts?

Yeah I think we probably should 🙂 @ATorrise Could you run `npm audit fix` to update the `npm-shrinkwrap.json` and resolve the vulnerability that's causing the Audit check to fail?

2023-05-11 16:12 UTC, t1m0thyj requested changes
Will approve once the Audit check is passing

2023-05-12 12:04 UTC, zFernand0 requested changes
did you run `npm audit fix --force` ?
if so, it might have applied breaking changes when updating `typedoc`.
nothing wrong, but we may want to address the `typescript` dependency, i.e. update to `"typescript": "^4.9.5"`

2023-05-12 13:50 UTC, t1m0thyj commented
If we update `typedoc` through `npm audit fix --force`, it will require us to update a number of other dev deps as well like `typescript`, `ts-jest`, and `jest` so they are all compatible with each other. I'm not opposed to doing this, but don't want to expand the scope of this PR either 😅

@ATorrise It may be easiest to revert back to the last commit before the `npm audit` (https://github.com/zowe/zowe-cli-ims-plugin/pull/57/commits/b894eea020de7835ea099de8377f3b59df5f2c55), and then run `npm audit fix` again without the `--force` flag to update only the Imperative package.

2023-05-12 20:05 UTC, t1m0thyj requested changes

2023-05-12 20:05 UTC, t1m0thyj commented on .github/workflows/zowe-cli-plugin.yml
>        uses: zowe-actions/octorelease-script@master
Please update to `zowe-actions/octorelease/script@v1`

2023-05-15 13:36 UTC, t1m0thyj approved these changes

2023-05-15 14:05 UTC, zFernand0 approved these changes

2023-05-15 14:05 UTC, merged